#!/usr/bin/env bun
/**
 * Generate `packages/cli/src/assets.generated.ts` from `packages/web/dist`.
 *
 * A compiled binary (`bun build --compile`) has no `packages/web/dist` on disk: `import.meta.dir`
 * resolves, but into the virtual `/$bunfs` filesystem. The only way to ship the web app inside the
 * binary is to import each built file with `with { type: "file" }`, which makes the bundler embed it
 * and hands back the path it lives at. Bun appends a *second* hash to that path, so it cannot be
 * reconstructed from the original filename — hence a generated lookup map rather than a convention.
 *
 * Vite hashes its own output filenames, so this must run after every `vite build`. `bun run build`
 * does both.
 *
 * The generated file is build output and is gitignored. Nothing may import it statically; the CLI
 * loads it through a `try`/`catch`ed dynamic import so a checkout without a web build still works.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const distDir = join(repoRoot, "packages/web/dist");
const outFile = join(repoRoot, "packages/cli/src/assets.generated.ts");

/** Every file under `dir`, as paths relative to it, with forward slashes, sorted. */
function walk(dir: string, prefix = ""): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    const rel = prefix ? `${prefix}/${entry}` : entry;
    if (statSync(abs).isDirectory()) out.push(...walk(abs, rel));
    else out.push(rel);
  }
  return out.sort();
}

let files: string[];
try {
  files = walk(distDir);
} catch {
  console.error(`gen-assets: no ${relative(repoRoot, distDir)} — run \`bun run --cwd packages/web build\` first`);
  process.exit(1);
}
if (!files.includes("index.html")) {
  console.error(`gen-assets: ${relative(repoRoot, distDir)} has no index.html`);
  process.exit(1);
}

// Relative specifiers, so the generated file is identical on every machine and in CI.
const fromCliSrc = relative(join(repoRoot, "packages/cli/src"), distDir).replaceAll("\\", "/");

const imports = files.map((f, i) => `import f${i} from "${fromCliSrc}/${f}" with { type: "file" };`);
const entries = files.map((f, i) => `  "/${f}": f${i},`);

writeFileSync(
  outFile,
  [
    // tsc cannot type a `with { type: "file" }` import of a .css or a Vite-hashed .js, and types
    // index.html as HTMLBundle rather than the string Bun actually hands back at runtime. The
    // committed assets.generated.d.ts is the declaration the rest of the CLI type-checks against.
    "// @ts-nocheck",
    "// GENERATED by scripts/gen-assets.ts — do not edit, do not commit.",
    "// Maps a request path to the file's embedded location inside the compiled binary.",
    ...imports,
    "",
    "export const ASSETS: Record<string, string> = {",
    ...entries,
    "};",
    "",
  ].join("\n"),
);

console.error(`gen-assets: wrote ${relative(repoRoot, outFile)} (${files.length} files)`);
